function plotResultPart3(gui,src,F,x)
% http://www.matlab-cookbook.com/recipes/0050_Plotting/0025_Distributions/0014_overlayGausHist.html
[genFIT,expFIT,Heat_WholeSale_Price,RHI,mirrFinanceRate,mirrReinvestmentRate,inflationFactor,Annual_Electricity_Generation,Annual_Heat_Generation,...
    tax_Rate,annualCost,DepreciationBuildingSchedule,DepreciationMachinerySchedule,...
    discountFactor,totalCapitalInvestment,numberMonteCarloScenarios,projectLifetime,annualOpex,loanRepaymentSchedule] = aaa_getCalculatedParameters(gui);


% cla(gui.R1C1Result3);
% set( gui.notesResult3, 'String', '');
%% NPV distribution
if strcmpi(get(src,'Tag'),'NPV')
    
    scale = 1000;
    F = F./scale;
    histogram(gui.R1C1Result3,F,100);
    xlabel(gui.R1C1Result3,'Distribution of net present values, £ 000');
    ylabel(gui.R1C1Result3,'Number of cases');
    
    prob = F;
    prob(prob<=0)=0;
    prob(prob>0)=1;
    prob = mean(prob);
    prob = prob*100; % express as percentage
    
    % update notes that is based on results
    notesForResultIII = sprintf(['%6.2f stochastic cases of the CHP AD project were simulated. The results indicate that given Year 1',...
        ' aggregate electricity and heat prices of %6.2f p/kWh and %6.2f p/kWh respectively (see tab "Prices and rates"), and given that these prices are annually inflated at the rate of %6.2f percent (see tab "Prices and rates")',...
        ' over %6.2f years (see tab "Cases/Lifetime/Seed"),',...
        ' the expected (i.e. mean) and median NPVs of the project are £%6.2f and £%6.2f respectively. The minimum and maximum NPVs are £%6.2f and £%6.2f respectively.'...,
        ' %3.2f percent of simulated cases had positive NPVs. This means that the probability of the project being feasible is %3.2f percent.\n',...
        ' Please see tab "Simulated data" for more information about the individual simulated cases.'],...
        [str2double(get(gui.editNumSimulationCases,'String'))...
        (str2double(get(gui.genFIT,'String'))+str2double(get(gui.expFIT,'String')))... 
        (str2double(get(gui.heatPrice,'String'))+str2double(get(gui.RHI,'String')))...
        str2double(get(gui.editInflationRate,'String'))...
        str2double(get(gui.editProjectHorizon,'String'))...
        mean(F)*scale median(F)*scale min(F)*scale max(F)*scale prob prob]);      
    set( gui.notesResult3, 'String', notesForResultIII);
    
end

%% MIRR distribution
if strcmpi(get(src,'Tag'),'MIRR')
    
    scale = 100; % express mirr in %
    histogram(gui.R1C1Result3,F*scale,100);
    xlabel(gui.R1C1Result3,'Distribution of modified internal rates of return (%)');
    ylabel(gui.R1C1Result3,'Number of cases');
    
    prob = F;
    prob(prob<=0)=0;
    prob(prob>0)=1;
    prob = mean(prob);
    prob = prob*100; % express as percentage

    % update notes that is based on results
    notesForResultIII = sprintf(['%6.2f stochastic cases of the CHP AD project were simulated. The results indicate that given Year 1',...
        ' aggregate electricity and heat prices of %6.2f p/kWh and %6.2f p/kWh respectively (see tab "Prices and rates"), and given that these prices are annually inflated at the rate of %6.2f percent (see tab "Prices and rates")',...
        ' over %6.2f years (see tab "Cases/Lifetime/Seed"),',...
        ' the expected (i.e. mean) and median MIRRs of the project are %6.2f percent and %6.2f percent respectively. The minimum and maximum MIRRs are %6.2f percent and %6.2f percent respectively. ',...
        ' %3.2f percent of simulated cases had positive rates of return.\n',...
        ' Please see tab "Simulated data" for more information about the individual simulated cases.'],...
        [str2double(get(gui.editNumSimulationCases,'String'))...
        (str2double(get(gui.genFIT,'String'))+str2double(get(gui.expFIT,'String')))... 
        (str2double(get(gui.heatPrice,'String'))+str2double(get(gui.RHI,'String')))...
        str2double(get(gui.editInflationRate,'String'))...
        str2double(get(gui.editProjectHorizon,'String'))...
        mean(F)*scale median(F)*scale min(F)*scale max(F)*scale prob]);      
    set( gui.notesResult3, 'String', notesForResultIII);
    
end

%% Breakeven electricity price distribution
if strcmpi(get(src,'Tag'),'BreakEvenElectricityPrice')
    
    histogram(gui.R1C1Result3,x,100); xlabel(gui.R1C1Result3,'Distribution of breakeven electricity prices');
    xlabel(gui.R1C1Result3,'Distribution of initial year breakeven elecricity prices, p/kWh');
    ylabel(gui.R1C1Result3,'Number of cases');
    
    prob = x;
    prob(prob<=0)=0;
    prob(prob>0)=1;
    prob = mean(prob);
    prob = prob*100; % express as percentage
    prob = 100-prob;

    % update notes that is based on results
    notesForResultIII = sprintf(['%6.2f stochastic cases of the CHP AD project were simulated. The results indicate that given Year 1 aggregate heat price of %6.2f p/kWh (see tab "Prices and rates"),'...
        ' the expected (i.e. mean) and median Year 1 aggregate breakeven electricity prices are  %6.2f p/kWh and %6.2f p/kWh respectively.',... 
        ' The minimum and maximum Year 1 aggregate breakeven electricity prices are %6.2f p/kWh and %6.2f p/kWh respectively.',...
        ' All Year 1 prices are annually inflated at the rate of %6.2f percent (see tab "Prices and rates") over the project lifetime of %6.2f years (see tab "Cases/Lifetime/Seed").',...
        ' Please see tab "Simulated data" for more information about the individual simulated cases.\n',...
        ' A positive breakeven electricity price means that the CHP AD project',...
        ' needs sale of electricity at that price to breakeven. A negative breakeven electricity price means that the CHP AD project is inherently profitable from sale of heat only and would',... 
        ' not need sale of electricity to breakeven.',...
        ' %3.2f percent of simulated cases had negative breakeven electricity prices. This means that %3.2f percent of cases would be profitable through sale of heat only. '],...
        [str2double(get(gui.editNumSimulationCases,'String'))...
        (str2double(get(gui.heatPrice,'String'))+str2double(get(gui.RHI,'String')))...
        mean(x) median(x) min(x) max(x) str2double(get(gui.editInflationRate,'String'))...
        str2double(get(gui.editProjectHorizon,'String')) prob prob]);
    
    set( gui.notesResult3, 'String', notesForResultIII);
    
end

%% Breakeven heat price distribution
if strcmpi(get(src,'Tag'),'BreakEvenHeatPrice')
    
    histogram(gui.R1C1Result3,x,100); xlabel(gui.R1C1Result3,'Distribution of breakeven heat prices');
    xlabel(gui.R1C1Result3,'Distribution of initial year breakeven heat prices, p/kWh');
    ylabel(gui.R1C1Result3,'Number of cases');
    
    prob = x;
    prob(prob<=0)=0;
    prob(prob>0)=1;
    prob = mean(prob);
    prob = prob*100; % express as percentage
    prob = 100-prob;
    
    % update notes that is based on results
    notesForResultIII = sprintf(['%6.2f stochastic cases of the CHP AD project were simulated. The results indicate that given Year 1 aggregate electricity price of %6.2f p/kWh (see tab "Prices and rates"),'...
        ' the expected (i.e. mean) and median Year 1 aggregate breakeven heat prices are  %6.2f p/kWh and %6.2f p/kWh respectively.',...
        ' The minimum and maximum Year 1 aggregate breakeven heat prices are %6.2f p/kWh and %6.2f p/kWh respectively.',...
        ' All Year 1 prices are annually inflated at the rate of %6.2f percent (see tab "Prices and rates") over the project lifetime of %6.2f years (see tab "Cases/Lifetime/Seed").',...
        ' Please see tab "Simulated data" for more information about the individual simulated cases.\n',...
        ' A positive breakeven heat price means that the CHP AD project',...
        ' needs sale of heat at that price to breakeven. A negative breakeven heat price means that the CHP AD project is inherently profitable from sale of electricity only and would',...
        ' not need sale of heat to breakeven.',...
        ' %3.2f percent of simulated cases had negative breakeven heat prices. This means that %3.2f percent of cases would be profitable through sale of electricity only. '],...
        [str2double(get(gui.editNumSimulationCases,'String'))...
        (str2double(get(gui.genFIT,'String'))+str2double(get(gui.expFIT,'String')))...
        mean(x) median(x) min(x) max(x) str2double(get(gui.editInflationRate,'String'))...
        str2double(get(gui.editProjectHorizon,'String')) prob prob]);
    
    set( gui.notesResult3, 'String', notesForResultIII);
    
end
end